### PR TITLE
Add azurewebsites placeholder to site name prompt

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**
Screen Shot 2020-04-06 at 3 24 55 PM

Fixes https://github.com/microsoft/vscode-azurefunctions/issues/1940

### CODE REVIEW

**Comment by nturinski** [comment]
I feel like this might be confusing.  Do you think people might think to type appname.azurewebsites.net?

**Comment by EricJizbaMSFT** [comment]
If they do, it'll tell them a "." is not allowed. If not this, what do you suggest?

**Comment by EricJizbaMSFT** [comment]
Gonna merge it so I can get a release candidate, but feel free to suggest something else

**Comment by nturinski** [comment]
Yeah, I'll think about it 🤔 I forgot, what was the reason we're adding that to the placeholder?

**Comment by EricJizbaMSFT** [comment]
https://github.com/microsoft/vscode-azurefunctions/issues/1940

**Pull request merged**
