### PR TITLE
Customize Wizard-integrated Activity tree items

### PR DESCRIPTION
**Pull request by alexweininger**
Goal: Make it easy to customize the wizard-integrated Activity tree items

I recommend looking at what these changes accomplish in https://github.com/microsoft/vscode-azurefunctions/pull/3255 before getting into the code changes here. 

To summarize: 
- Added a new `displayOptions?: ActivityTreeItemOptionsFactory` property to `ExecuteActivityContext`. Which if set controls how the activity is displayed in the Activity Log.
- If left unset, the Wizard will use the new `CreateOrDeleteActivityOptions` (what used to be ExecuteActivity) by default. 
- Added an `ActivityOptionsFactoryBase` util class to remove boilerplate from creating a custom `ActivityTreeItemOptionsFactory`

### CODE REVIEW

**Comment by bwateratmsft** [comment]
The way the activity API is meant to be implemented, in this case, would be for the Functions extension to implement its own inheritor of the `ActivityBase` class, or even an entirely separate implementation of the `Activity` interface. The four events (start, progress, success, error) give control over all aspects of the display that the client extensions are meant to control (context values, label, children). I don't see the need to add a fifth options set.

**Comment by alexweininger** [comment]
> The way the activity API is meant to be implemented, in this case, would be for the Functions extension to implement its own inheritor of the `ActivityBase` class, or even an entirely separate implementation of the `Activity` interface. The four events (start, progress, success, error) give control over all aspects of the display that the client extensions are meant to control (context values, label, children). I don't see the need to add a fifth options set.

Got it. I think I can refactor what I've done here so that I don't need to add the options property to the `Activity` interface.

**Comment by alexweininger** [comment]
@bwateratmsft 

I've removed the `options` property from `Activity`. This means https://github.com/microsoft/vscode-azureresourcegroups/pull/342 is no longer needed.

With this change, everything shown in https://github.com/microsoft/vscode-azurefunctions/pull/3255 still works. Adding the `options` property to `Activity` made my life unnecessarily hard...

**Comment by alexweininger** [comment]
Closing in favor of #1212

**Pull request closed without merging**
