### PR TITLE
Update swagger.json for vfs.getItem

### PR DESCRIPTION
**Pull request by nturinski**

### CODE REVIEW

**Comment by nturinski** [comment]
Hmm, I'm not sure because I'm just copying and pasting the output from the generated file. Maybe if did it on a Mac?

**Comment by EricJizbaMSFT** [comment]
Looks like you changed it from 4-space tabs to 2-space tabs. Should be a VS Code setting, not an OS thing

**Comment by nturinski** [comment]
I haven't changed it to 2-space tabs on my settings though.

image

**Comment by nturinski** [comment]
Good catches

**Pull request merged**
